sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

stages:
  - name: test
    # require the event type to not be a semantic release tag.
    if: NOT tag =~ ^\d+\.\d+\.\d+$

jobs:
  include:
    - stage: test
      node_js: 'lts/carbon'
      script:
        - yarn run lint
        - yarn test
        - yarn run coveralls
   -  stage: test
      node_js: 'lts/boron'
      script:
        - yarn run lint
        - yarn test