# Semverist config begins

semveristBehaviors:
  inheritence: lazySemverist
  lazySemverist:
    preReleaseForwards: false
    attributes: false
  default: false
  defaultName: default
  groups: false
  mergeStrategy: merge
  preReleasePattern: "[a-z]"
groups:
  example:
    members:
      - example
prereleaseOrdering: {}
directoryFileIgnorePattern: "json$"
converterType: default
semverishObjectLocation: ""
composer:
  composerType: default  # can be default (object) or directory
  destination: ""
  priority: default
