processTemplates:
  -
    -
      source:
        target: swaggerSrc
        plugin: originalSchemeSource
      transform:
        plugin: tokenTemplateValues
      destination:
        target: swaggerSrc
