# template file.
"2":
  swaggerSrc:
    apiName: 'Swagger Example APi' #required
    apiVersion: '3.14.0' #required
    apiDescription: 'An example Api for example corp.' #optional
    termsOfService: '' #optional
    contact: #optional
      name: 'Dave Example' #contact name
      url: 'http://example.com'  #http://example.com
      email: 'example@example.com' #example@example.com
    license: #optional
      name: "apache 2.0"
      url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    apiHost: "example.com"
    apiBasePath: "/api" # must start with a leading slash.
    schemes:
      process: !!js/function 'function() { return JSON.stringify(this.items); }'
      items:
        - "https"
        - "http"
    consumes:
      -
        mime:
          type: "vnd.api+json"
          comma: false
    produces:
      -
        mime:
          type: "vnd.api+json"
          comma: false
    definitions:
      process: !!js/function 'function() { return JSON.stringify(this.items); }'
      items:
        example:
          type: "object"
          properties:
            id:
              type: "integer"
              format: "int64"
            name:
              type: "string"
        example2:
          type: "object"
          properties:
            name:
              type: "string"
    parameters:
      process: !!js/function 'function() { return JSON.stringify(this.items); }'
      items:
        skipParam:
          name: skip
          in: query
          description: number of items to skip
          required: true
          type: integer
          format: int32
    responses:
      process: !!js/function 'function() { return JSON.stringify(this.items); }'
      items:
        notFound:
          description: Entity not found.
        IllegalInput:
          description: Illegal input for operation.
        GeneralError:
          description: General Error
          schema:
            $ref: '#/definitions/example2'
    securityDefinitions:
      process: !!js/function 'function() { return JSON.stringify(this.items); }'
      items:
        api_key:
          type: apiKey
          name: api_key
          in: header
        petstore_auth:
          type: oauth2
          authorizationUrl: "http://swagger.io/api/oauth/dialog"
          flow: implicit
          scopes:
            write.pets: modify pets in your account
            read.pets: read your pets
    security:
      process: !!js/function 'function() { return JSON.stringify(this.items); }'
      items:
        petstore_auth:
          - write:pets
          - read:pets
    tags:
      process: !!js/function 'function() { return JSON.stringify(this.items); }'
      items:
        - name: pet
          description: Pets operations
          externalDocs:
            description: pet docs
            url: http://example.com/pet
        - name: carrot
          description: Vegetable
    externalDocs:
      description: Further api docs
      url: http://example.com/docs
